"use client";

import Image from "next/image";
import gptBagDemo from "../../assets/images/GPT_Bag_Demo.png";
import { Button } from "./button";
import { CharacterTextReveal } from "./character-text-reveal";

const PREORDER_CART_URL =
  "https://potatochipsai.myshopify.com/cart/53229203620203:1";
const CHIPS_AI_PRICE = "$11.99";
const QUANTITY_OPTIONS = Array.from({ length: 30 }, (_, index) => index + 1);

export function PreorderProductPage() {
  return (
    <section className="marketing-preorder-page marketing-page-light bg-[#f7f7f7] text-black">
      <div className="marketing-container pt-32 pb-24 sm:pt-32 sm:pb-28 lg:pt-36 lg:pb-32">
        <div className="marketing-rail grid gap-12 lg:grid-cols-[minmax(22rem,0.45fr)_minmax(28rem,0.55fr)] lg:items-start lg:gap-16">
          <div className="max-w-[42rem]">
            <h1 className="max-w-5xl font-display text-[clamp(2.45rem,5.3vw,4.55rem)] font-normal leading-[0.95] tracking-[-0.05em] text-balance text-black">
              <CharacterTextReveal text="Chips AI" />
            </h1>
            <p
              aria-live="polite"
              className="mt-6 font-google-sans text-[1.18rem] font-normal leading-none tracking-normal text-black"
            >
              {CHIPS_AI_PRICE}
            </p>

            <div className="mt-8 w-full max-w-[20rem] sm:max-w-sm">
              <label className="marketing-form-label" htmlFor="preorder-quantity">
                Quantity
              </label>
              <select
                className="marketing-select font-google-sans text-[0.9rem] font-semibold"
                defaultValue="1"
                id="preorder-quantity"
                name="quantity"
              >
                {QUANTITY_OPTIONS.map((quantity) => (
                  <option key={quantity} value={quantity}>
                    {quantity}
                  </option>
                ))}
              </select>
            </div>

            <div className="mt-8 max-w-[46rem] space-y-5 text-[1.04rem] leading-[1.86] text-black/80 lg:text-[1.12rem]">
              <p>
                The future engine behind the people in AI factories for the age
                of AI reasoning—now in full production.
              </p>
              <p className="font-semibold">
                If the taste sucks, we&apos;re in a bubble. If the taste is good,
                the hype is real.
              </p>
            </div>

            <ul className="mt-8 list-disc space-y-2 pl-5 text-[1.04rem] leading-[1.86] text-black/80 lg:text-[1.12rem]">
              <li>Real ingredients, artificial intelligence</li>
              <li>Recipe generated by Claude Opus 4.7 Adaptive</li>
              <li>Recyclable packaging</li>
            </ul>

            <div className="marketing-fade-up marketing-fade-up-delay-1 relative z-30 mt-8 w-full max-w-[20rem] pointer-events-auto sm:max-w-sm">
              <Button
                href={PREORDER_CART_URL}
                className="marketing-hero-button relative z-30 min-w-0 w-full"
              >
                Pre-order Now
              </Button>
            </div>
          </div>

          <div className="relative flex min-h-[34rem] items-center justify-center overflow-hidden rounded-[15px] bg-[#f5f5f5] px-6 py-10 shadow-[0_1.6rem_4rem_rgba(0,0,0,0.08)] sm:min-h-[42rem] lg:min-h-[50rem]">
            <div
              className="absolute inset-x-12 bottom-16 h-16 bg-black/10 blur-2xl"
              aria-hidden="true"
            />
            <div className="relative z-10 flex w-full flex-col items-center">
              <Image
                src={gptBagDemo}
                alt="Potato Chips AI bag selected for pre-order."
                loading="eager"
                sizes="(max-width: 1024px) 78vw, 42vw"
                className="h-auto w-full max-w-[21rem] drop-shadow-[0_2rem_3rem_rgba(0,0,0,0.38)] sm:max-w-[28rem] lg:max-w-[30rem]"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
